### ISSUE TITLE
Docker Kong and Heroku

### ISSUE THREAD

**Issue by roth-mike** [heroku/heroku-kong#20]
Is there any reason why we shouldn't deploy Kong using Docker on Heroku? If not, what are the benefits of using the `heroku-kong-buildpack` over deploying using Docker on Heroku? We're having issues running `0.13.1` with the buildpack.

**Comment by mars** [comment]
We have not worked on this buildpack since Kong version 0.11. It was a proof-of-concept.

Reasons that I can remember for why Docker did not work for us originally (these may no longer be the case with the current version):

- Kong uses multiple network ports, and thus requires config customization to make it work with Heroku's single web listener `$PORT` 
- Kong uses a file-based configuration, and thus requires an adapter to translate Heroku config vars into runtime config files

Definitely use Docker if that works! Would love to hear about your results.

**Comment by mars** [comment]
I've created a [PR for Kong 0.14.0](https://github.com/heroku/heroku-kong/pull/21).

Feel free to try it out and please give feedback on the PR.

**Comment by mars** [comment]
This app now deploys Kong 0.14.1 from master!
